### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by patrickjquinn** [angeloraso/capacitor-background-mode#1]
Hi there,

It looks like you've yet to upgrade your plugin for Capacitor 5 support meaning it's breaking builds on Android (which now require a namespace to be specified in the build.gradle).

Whenever you get a chance, could you run the upgrade assistant on your plugin?

Thank you!

**Comment by angeloraso** [comment]
Hi there!

Right now, I'm short on time. When I have a chance, I'll make space in my schedule to update this plugin.

If you need it updated soon, you can create a pull request with the necessary changes. I promise to take the time to review it as soon as possible.

**Comment by angeloraso** [comment]
It's done
